### ISSUE TITLE
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 3: invalid continuation byte

### ISSUE THREAD

**Issue by JCStarry** [wroscoe/donkey#118]
I built a donkey car by myself ,and just fellow the steps on "http://www.donkeycar.com/" . I use donkey_2.image for raspberry pi3. I can run the "python3 manage.py  drive " normally and record data for training a autopilot model , but when I run " python3 manage.py train",always get a " UnicodeDecodeError". does any one meet the same error before? and how can I fix it , thank a lot!  

(env)pi@raspberrypi:~/d2 $ python3 manage.py train --tub=tub_7_17-08-28 --model=models
Using TensorFlow backend.
Tub does exist
/home/pi/donkeycar/donkeycar/parts/ml/keras.py:56: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  nb_val_samples=steps*.2)
/home/pi/donkeycar/donkeycar/parts/ml/keras.py:56: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., validation_data=None, callbacks=[<keras.ca..., steps_per_epoch=10, verbose=1, validation_steps=2.0, epochs=100)`
  nb_val_samples=steps*.2)
Epoch 1/100
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/env/lib/python3.4/site-packages/keras/utils/data_utils.py", line 560, in data_generator_task
    generator_output = next(self._generator)
  File "/home/pi/donkeycar/donkeycar/parts/stores/tub.py", line 214, in train_gen
    batch = next(batch_gen)
  File "/home/pi/donkeycar/donkeycar/parts/stores/tub.py", line 198, in batch_gen
    record_list.append(next(record_gen))
  File "/home/pi/donkeycar/donkeycar/parts/stores/tub.py", line 185, in record_gen
    record = self.get_record(i)
  File "/home/pi/donkeycar/donkeycar/parts/stores/tub.py", line 149, in get_record
    json_data = self.get_json_record(ix)
  File "/home/pi/donkeycar/donkeycar/parts/stores/tub.py", line 112, in get_json_record
    json_data = json.load(fp)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/home/pi/env/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 3: invalid continuation byte

 1/10 [==>...........................] - ETA: 128s - loss: 7.0849 - angle_out_loss: 7.8323 - throttle_out_loss: 0.3589Traceback (most recent call last):
  File "manage.py", line 148, in <module>
    train(tub, model)
  File "manage.py", line 124, in train
    kl.train(train_gen, None, saved_model_path=model_path)
  File "/home/pi/donkeycar/donkeycar/parts/ml/keras.py", line 56, in train
    nb_val_samples=steps*.2)
  File "/home/pi/env/lib/python3.4/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/env/lib/python3.4/site-packages/keras/engine/training.py", line 1809, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by tawnkramer** [comment]
You will want to move the data set to your pc for training. Please check http://docs.donkeycar.com/guide/train_autopilot/

**Comment by JCStarry** [comment]
Thanks for your reply ! !, I have tried to move the data set to my Ubuntu PC. I  have installed  latest donkeycar and tensorflow . but when I use the same commands to train a pilot model I always get the same error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2: invalid start byte" 

I don't how to do next , expecting any reply , thanks a lot!

**Comment by JCStarry** [comment]
I also tried to install donkeycar and TensorFlow in virtualenv ,but same errors    = =!

**Comment by tawnkramer** [comment]
You can not specify a dir as the output file. 
```python3 manage.py train --tub=tub_7_17-08-28 --model=models```
should be
```python3 manage.py train --tub=tub_7_17-08-28 --model=mymodel.h5```

**Comment by JCStarry** [comment]
Thanks for your reply！！I have tried the command as your advice，but the same “utf-8” error 。。QAQ 
here is the detail。。= =!

`(tensorflow) jc@jc-pc:~/ProjectX/donkey_car/d6$ python3 manage.py train --tub=tub_7_17-08-28  --model=mymodel.h5
Using TensorFlow backend.
loading config file: /home/jc/ProjectX/donkey_car/d6/config.py
config loaded
Tub does exist
Epoch 1/100
2017-09-21 12:00:02.482846: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 12:00:02.482873: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 12:00:02.482880: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 12:00:02.482887: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-21 12:00:02.482895: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/home/jc/ProjectX/donkey_car/d6/donkeycar/donkeycar/parts/stores/tub.py", line 222, in train_gen
    batch = next(batch_gen)
  File "/home/jc/ProjectX/donkey_car/d6/donkeycar/donkeycar/parts/stores/tub.py", line 206, in batch_gen
    record_list.append(next(record_gen))
  File "/home/jc/ProjectX/donkey_car/d6/donkeycar/donkeycar/parts/stores/tub.py", line 193, in record_gen
    record = self.get_record(i)
  File "/home/jc/ProjectX/donkey_car/d6/donkeycar/donkeycar/parts/stores/tub.py", line 157, in get_record
    json_data = self.get_json_record(ix)
  File "/home/jc/ProjectX/donkey_car/d6/donkeycar/donkeycar/parts/stores/tub.py", line 120, in get_json_record
    json_data = json.load(fp)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/home/jc/tensorflow/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2: invalid start byte

  1/100 [..............................] - ETA: 138s - loss: 5.1415 - angle_out_loss: 5.7123 - throttle_out_loss: 0.3831Traceback (most recent call last):
  File "manage.py", line 172, in <module>
    train(cfg, tub, model)
  File "manage.py", line 145, in train
    kl.train(combined_gen(train_gens), combined_gen(val_gens), saved_model_path=model_path)
  File "/home/jc/ProjectX/donkey_car/d6/donkeycar/donkeycar/parts/ml/keras.py", line 61, in train
    validation_steps=steps*.2)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration`

**Comment by tawnkramer** [comment]
Can you share your dataset somewhere on Dropbox or google drive? I'd like
to see if we get the same error.

**Comment by JCStarry** [comment]
Thanks a lot!!
my dataset folder is tub_7_17-08-28,  below is the google drive link , the dataset is in a .zip file 

[https://drive.google.com/open?id=0B5OxKaalqD0ARERHTVd5Q1pLclk](url)

**Comment by tawnkramer** [comment]
I'm taking a look now. I was able to reproduce the problem. It looks like about 30 or so of your records from record_4530.json to 4345 have bad characters. Did you edit or run any scripts on your data after recording?

**Comment by tawnkramer** [comment]
can you try a ```git pull``` in donkey and get latest. Then try regenerating your manage.py in a new dir with ```donkey createcar --path ~/d3```. Move your data to the ~/d3/data dir, then run the new command
```python manage.py clean --fix```. This command will find and remove bad records. Then try running training.

**Comment by tawnkramer** [comment]
please do let us know if this is happening a lot for you. I haven't seen this reported before. Would be ideal to fix cause instead of removing bad records.
