### ISSUE TITLE
Error while driving. Adafruit servo hat write error. 

### ISSUE THREAD

**Issue by wroscoe** [wroscoe/donkey#18]
After driving 10 minutes, the car stopped responding and updating images. This was the error from on the pi.

```
/usr/lib/python3/dist-packages/picamera/encoders.py:545: PiCameraResolutionRoun$
  width, height, fwidth, fheight)))
123
angle: -6   throttle: 46
remote client: {"angle": "-6", "throttle": "46"}
Traceback (most recent call last):
  File "demos/drive_pi.py", line 55, in <module>
    car.start()
  File "/home/pi/code/donkey/donkey/vehicles.py", line 39, in start
    self.steering_actuator.update(angle)
  File "/home/pi/code/donkey/donkey/actuators.py", line 73, in update
    self.pwm.set_pwm(self.channel, 0, pulse)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Adafruit_PCA9685/P$
    self._device.write8(LED0_ON_L+4*channel, on & 0xFF)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Adafruit_GPIO/I2C.$
    self._bus.write_byte_data(self._address, register, value)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Adafruit_PureIO/sm$
    self._device.write(data)
OSError: [Errno 5] Input/output error

```

**Comment by kclim2** [comment]
We trying to use arduino to replace the PCA9685 and get similar i2c error. Ant tips to fix the error?
