### ISSUE TITLE
train data error

### ISSUE THREAD

**Issue by mexbo** [wroscoe/donkey#261]
There was a error when I trained the data.
How am I gonna fix it?
`Traceback (most recent call last):
  File "/home/donkeycar/d2/manage.py", line 183, in <module>
    train(cfg, tub, model)
  File "/home/donkeycar/d2/manage.py", line 166, in train
    train_split=cfg.TRAIN_TEST_SPLIT)
  File "/home/donkeycar/Downloads/donkeycar/donkeycar/parts/keras.py", line 67, in train
    validation_steps=steps*(1.0 - train_split)/train_split)
  File "/home/donkeycar/env/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/donkeycar/env/lib/python3.5/site-packages/keras/engine/training.py", line 2042, in fit_generator
    class_weight=class_weight)
  File "/home/donkeycar/env/lib/python3.5/site-packages/keras/engine/training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "/home/donkeycar/env/lib/python3.5/site-packages/keras/engine/training.py", line 1378, in _standardize_user_data
    exception_prefix='input')
  File "/home/donkeycar/env/lib/python3.5/site-packages/keras/engine/training.py", line 144, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected img_in to have shape (None, 120, 160, 3) but got array with shape (128, 160, 120, 3)
`

**Comment by mexbo** [comment]
this error is happened in my ubuntu server.My virtual env is python3.5.

**Comment by mexbo** [comment]
OK,I found the problem. https://github.com/wroscoe/donkey/issues/200
