### ISSUE TITLE
Camera resolution

### ISSUE THREAD

**Issue by NikulausRui** [wroscoe/donkey#299]
Thank you very much for providing this open source code. Now I have some problems. After three days of processing, it is still unresolved. Would you please take a look at it for me?
I set the camera resolution to (600,800) at config.py, and then trained mypilot with this configuration. When I was driving with mypilots, this problem occurred:

Traceback (most recent call last):
File "manage.py", line 190, in <module>
Drive (CFG, model_path = args['--model'], use_joystick=args['--js'], use_chaos=args['--chaos'])
File "manage.py", line 131, in drive
Max_loop_count=cfg.MAX_LOOPS)
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/vehicle.py", line 93, in start
Self.update_parts ()
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/vehicle.py", line 129, in update_parts
Outputs = p.run (*inputs)
File "/home/pi/env/lib/python3.5/site-packages/donkeycar/parts/keras.py", line 74, in run
Angle_binned, throttle = self.model.predict (img_arr)
File "/ home/pi/env/lib/python 3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1327, in prediction
X, self._standardize_user_data, x =
File "/ home/pi/env/lib/python 3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 765, in_standardize_user_data
Exception_prefix='input')
File "/ home/pi/env/lib/python 3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/training_utils.py", line 192, in standardize_input_data
'but got array with shape' + str (data_shape))
ValueError: Error when checking input: expected img_in to have shape (120, 160, 3) but got array with shape (600, 800, 3)

This is my configuration:

Import OS
#PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname (os.path.realpath (__file__))
DATA_PATH = os.path.join (CAR_PATH,'data')
MODELS_PATH = os.path.join (CAR_PATH,'models')
#VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 100000
#CAMERA
CAMERA_RESOLUTION = (600, 800) height (width)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ
#STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 500
STEERING_RIGHT_PWM = 300
#THROTTLE
THROTTLE_CHANNEL = 0
THROTTLE_FORWARD_PWM = 400
THROTTLE_STOPPED_PWM = 360
THROTTLE_REVERSE_PWM = 330
#TRAINING
BATCH_SIZE = 128
TRAIN_TEST_SPLIT = 0.8
#JOYSTICK
USE_JOYSTICK_AS_DEFAULT = False
JOYSTICK_MAX_THROTTLE = 0.25
JOYSTICK_STEERING_SCALE = 1
AUTO_RECORD_ON_THROTTLE = True
TUB_PATH = os.path.join (CAR_PATH,'tub') if using a single tub
#ROPE.DONKEYCAR.COM
ROPE_TOKEN= "GET A TOKEN AT ROPE.DONKEYCAR.COM"

Thank you very much!

**Comment by huseman21** [comment]
need more information on how to correct this. I have the same issue.  When I change the resolution in karas.py the results do not change.
