### ISSUE TITLE
donkey tubpilot 

### ISSUE THREAD

**Issue by NikulausRui** [wroscoe/donkey#314]
When I run donkey tubplot ./tub --model ./models/mypilot,this mistake was occurred.Any ideas on how to solve this problem?
Traceback (most recent call last):
  File "/usr/local/bin/donkey", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.5/dist-packages/donkeycar/management/base.py", line 445, in execute_from_command_line
    c.run(args[2:])
  File "/usr/local/lib/python3.5/dist-packages/donkeycar/management/base.py", line 365, in run
    self.plot_predictions(args.config, args.tubs, args.model)
  File "/usr/local/lib/python3.5/dist-packages/donkeycar/management/base.py", line 381, in plot_predictions
    gen = tg.get_batch_gen(None, None, batch_size=len(tg.df),shuffle=False, df=tg.df)
TypeError: get_batch_gen() got multiple values for argument 'batch_size'

**Comment by joelkny97** [comment]
I am getting a similar error when I try to plot the predictions, has this issue been fixed and if so, what is the solution ?
