### ISSUE TITLE
Timeout error with drive.py script, same script works in jupyter

### ISSUE THREAD

**Issue by wroscoe** [wroscoe/donkey#41]
When I run drive.py --remote <server url> The connection to the server never completes. When I Ctrl-C I see this traceback showing it's getting stuck when requests trys to make a connection. 

If I open jupyter notebook and use the same drive script, it works. 

Maybe this has something to do with cashed ip addresses in bash?

```
^CTraceback (most recent call last):
  File "scripts/drive.py", line 57, in <module>
    car.start()
  File "/home/pi/donkey/donkey/vehicles.py", line 33, in start
    milliseconds)
  File "/home/pi/donkey/donkey/remotes.py", line 60, in decide
    'json': json.dumps(data)}) #hack to put json in file 
  File "/usr/lib/python3/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 154, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 133, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
KeyboardInterrupt

```

**Comment by wroscoe** [comment]
The cause of this was that I was using the wrong remote IP address. I was using 192.162.1.2 instead of 192.168.1.2. 

This is also the traceback for the internet connection problems people were having while racing today.
