### ISSUE TITLE
Running Docker image on Ubuntu 14.04LTS fails

### ISSUE THREAD

**Issue by 094459** [wroscoe/donkey#90]
I am following the instructions from the google doc, and using the following instructions:

git clone http://github.com/wroscoe/donkey.git
cd donkey
sudo bash start-server.sh

The process fails with the following error.

~/donkey$ sudo bash start-server.sh 
start-server: Running Donkey server container...
Loading modules for server.
Starting Donkey Server...
Using TensorFlow backend.
Traceback (most recent call last):
  File "/donkey/scripts/serve.py", line 12, in <module>
    w = dk.remotes.DonkeyPilotApplication()
  File "/donkey/donkey/remotes.py", line 175, in __init__
    self.pilots = ph.default_pilots()
  File "/donkey/donkey/pilots.py", line 84, in default_pilots
    pilot_list = self.pilots_from_models()
  File "/donkey/donkey/pilots.py", line 71, in pilots_from_models
    models_list = [f for f in os.scandir(self.models_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/root/mydonkey/models'

I have had a search and could not find any clues, so am wondering whether I am being dense and this is something really simple or whether there is a genuine issue.

Many thanks.

**Comment by 094459** [comment]
I went through the slack channel and found the following which fixed my problem:

`bash start-server.sh -d` to get the docker terminal. Then running `python scripts/setup.py`, then exiting docker and rerunning `bash start-server.sh`
