### ISSUE TITLE
JSON decoder error on startup, fixed by restarting server

### ISSUE THREAD

**Issue by twhume** [wroscoe/donkey#93]
Occasionally when starting drive.py on the Pi, I would see the following error:

pi@raspberrypi:~/donkey $ python scripts/drive.py --remote http://172.20.10.5:8887
Detected running on rasberrypi. Only importing select modules.
Using TensorFlow backend.
center: 410
PiVideoStream loaded.. .warming camera
/usr/lib/python3/dist-packages/picamera/encoders.py:544: PiCameraResolutionRounded: frame size rounded up from 160x120 to 160x128
  width, height, fwidth, fheight)))
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/donkey/donkey/remotes.py", line 79, in update
    self.state['milliseconds'],)
  File "/home/pi/donkey/donkey/remotes.py", line 140, in decide
    data = json.loads(r.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

I've not managed to get repro steps; I found that restarting the Docker container and then retrying the drive.py script with the same arguments worked.

**Comment by wroscoe** [comment]
This is an issue when non-json chars or sequences are passed. I haven't seen this recently in the new version.
